
#To execute on Chrome enable browser.name =GC and for Edge, enable browser.name=ME
browser.name=GC
#browser.name=ME


AssignedTo=priyanka.singh@bajajfinserv.in
BugEnvironment=IT UAT
BugDetectedIn=Automation Testing
BugSeverity=Minor
Devices=NA
OS=NA
BuildNumber=NA
AreaPath=ExperiaPortal_Tasks
APIEndpoint=https://bfldashboards-automations.azurewebsites.net/createapi/createBugWorkitem
#App urls for B2C and B2B respectively
#App.url=https://uatb2c.bajajfinserv.in/
App.url=https://cont-sites.bajajfinserv.in/MyAccountLogin#;
#App.url=https://experia-uat.bajajfinserv.in
#App.url=http://172.30.1.142:3000/CHPS/CompleteHealthProtectSupreme.aspx
ReRun=True
#ReRun=False
