
#To execute on Chrome enable browser.name =GC and for Edge, enable browser.name=ME
browser.name=GC
#browser.name=ME

AssignedTo=Priyanka Singh <priyanka.singh@bajajfinserv.in>
BugEnvironment=IT UAT
BugDetectedIn=Automation Testing
BugSeverity=Minor
Devices=NA
OS=NA
BuildNumber=NA
AreaPath=ExperiaPortal_Tasks
APIEndpoint=https://prod-23.centralindia.logic.azure.com:443/workflows/d8accf501b6a472aa59c40cef4d4feba/triggers/manual/paths/invoke?api-version=2016-10-01&sp=/triggers/manual/run&sv=1.0&sig=9vshehyqyNhmq09nyw-NMMzx-vAVN4_B6ywraLBqtRY

#App urls for B2C and B2B respectively
#App.url=https://uatb2c.bajajfinserv.in/
App.url=https://cont-sites.bajajfinserv.in/MyAccountLogin#;
#App.url=https://experia-uat.bajajfinserv.in
#App.url=http://172.30.1.142:3000/CHPS/CompleteHealthProtectSupreme.aspx
ReRun=True
#ReRun=False

